// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlQjpu9f_ymRvuVO0Ycjvji3_fPUkXAI',
    appId: '1:653406555075:web:88b498ffbb526a7e690b76',
    messagingSenderId: '653406555075',
    projectId: 'portfolio-4ac6f',
    authDomain: 'portfolio-4ac6f.firebaseapp.com',
    storageBucket: 'portfolio-4ac6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPJyEsSfWIdocowlUc0eSrY1NXy48YvZc',
    appId: '1:653406555075:android:b9c59624f53426b7690b76',
    messagingSenderId: '653406555075',
    projectId: 'portfolio-4ac6f',
    storageBucket: 'portfolio-4ac6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhO4cFpxj_-a2GuacpA2ziEsV9bzt9Sok',
    appId: '1:653406555075:ios:e962465e8d5a0037690b76',
    messagingSenderId: '653406555075',
    projectId: 'portfolio-4ac6f',
    storageBucket: 'portfolio-4ac6f.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhO4cFpxj_-a2GuacpA2ziEsV9bzt9Sok',
    appId: '1:653406555075:ios:2ecdee245687241c690b76',
    messagingSenderId: '653406555075',
    projectId: 'portfolio-4ac6f',
    storageBucket: 'portfolio-4ac6f.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
