// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOmbXolZ8_Vu8UjiXVTomHS58E-YdzqBg',
    appId: '1:433656122300:web:22eb91ddc57e99c1ebf9b9',
    messagingSenderId: '433656122300',
    projectId: 'fir-7056e',
    authDomain: 'fir-7056e.firebaseapp.com',
    databaseURL: 'https://fir-7056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-7056e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIR7Su7ZL5rDF1UlTte9obz0HShNuCCdg',
    appId: '1:433656122300:android:1d6835c42a2f996aebf9b9',
    messagingSenderId: '433656122300',
    projectId: 'fir-7056e',
    databaseURL: 'https://fir-7056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-7056e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLnEdiKVjI4kVogf4gWLqdQ-17m6aEJzY',
    appId: '1:433656122300:ios:fed84a0264df1db6ebf9b9',
    messagingSenderId: '433656122300',
    projectId: 'fir-7056e',
    databaseURL: 'https://fir-7056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-7056e.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLnEdiKVjI4kVogf4gWLqdQ-17m6aEJzY',
    appId: '1:433656122300:ios:8fc3beb1484b6547ebf9b9',
    messagingSenderId: '433656122300',
    projectId: 'fir-7056e',
    databaseURL: 'https://fir-7056e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-7056e.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
